package jp.momotown.datasource;

import java.util.ArrayList;
import java.util.List;

import com.google.visualization.datasource.base.TypeMismatchException;
import com.google.visualization.datasource.datatable.ColumnDescription;
import com.google.visualization.datasource.datatable.DataTable;
import com.google.visualization.datasource.datatable.value.ValueType;

public class BattingResultDataTable extends DataTable {

	private static final BattingResultDataTable instance = new BattingResultDataTable();

	public BattingResultDataTable() {
  	List<ColumnDescription> cd = new ArrayList<ColumnDescription>();
		cd.add(new ColumnDescription("id",		ValueType.NUMBER,	"ID"));
		cd.add(new ColumnDescription("name",	ValueType.TEXT,		"名称"));
		
		addColumns(cd);
		
		try {
			addRowFromValues(1,		"投安");
			addRowFromValues(154,	"投安");
			addRowFromValues(155,	"投安");
			addRowFromValues(2,		"捕安");
			addRowFromValues(156,	"捕安");
			addRowFromValues(157,	"捕安");
			addRowFromValues(3,		"一安");
			addRowFromValues(158,	"一安");
			addRowFromValues(159,	"一安");
			addRowFromValues(4,		"二安");
			addRowFromValues(160,	"二安");
			addRowFromValues(161,	"二安");
			addRowFromValues(5,		"三安");
			addRowFromValues(162,	"三安");
			addRowFromValues(163,	"三安");
			addRowFromValues(6,		"遊安");
			addRowFromValues(164,	"遊安");
			addRowFromValues(165,	"遊安");
			addRowFromValues(7,		"左安");
			addRowFromValues(166,	"左安");
			addRowFromValues(167,	"左安");
			addRowFromValues(8,		"中安");
			addRowFromValues(168,	"中安");
			addRowFromValues(169,	"中安");
			addRowFromValues(9,		"右安");
			addRowFromValues(170,	"右安");
			addRowFromValues(171,	"右安");
			addRowFromValues(10,	"投２");
			addRowFromValues(172,	"投２");
			addRowFromValues(173,	"投２");
			addRowFromValues(11,	"捕２");
			addRowFromValues(174,	"捕２");
			addRowFromValues(175,	"捕２");
			addRowFromValues(12,	"一２");
			addRowFromValues(176,	"一２");
			addRowFromValues(177,	"一２");
			addRowFromValues(13,	"二２");
			addRowFromValues(178,	"二２");
			addRowFromValues(179,	"二２");
			addRowFromValues(14,	"三２");
			addRowFromValues(180,	"三２");
			addRowFromValues(181,	"三２");
			addRowFromValues(15,	"遊２");
			addRowFromValues(182,	"遊２");
			addRowFromValues(183,	"遊２");
			addRowFromValues(16,	"左２");
			addRowFromValues(184,	"左２");
			addRowFromValues(185,	"左２");
			addRowFromValues(17,	"中２");
			addRowFromValues(186,	"中２");
			addRowFromValues(187,	"中２");
			addRowFromValues(18,	"右２");
			addRowFromValues(188,	"右２");
			addRowFromValues(189,	"右２");
			addRowFromValues(19,	"投３");
			addRowFromValues(190,	"投３");
			addRowFromValues(191,	"投３");
			addRowFromValues(20,	"捕３");
			addRowFromValues(192,	"捕３");
			addRowFromValues(193,	"捕３");
			addRowFromValues(21,	"一３");
			addRowFromValues(194,	"一３");
			addRowFromValues(195,	"一３");
			addRowFromValues(22,	"二３");
			addRowFromValues(196,	"二３");
			addRowFromValues(197,	"二３");
			addRowFromValues(23,	"三３");
			addRowFromValues(198,	"三３");
			addRowFromValues(199,	"三３");
			addRowFromValues(24,	"遊３");
			addRowFromValues(200,	"遊３");
			addRowFromValues(201,	"遊３");
			addRowFromValues(25,	"左３");
			addRowFromValues(202,	"左３");
			addRowFromValues(203,	"左３");
			addRowFromValues(26,	"中３");
			addRowFromValues(204,	"中３");
			addRowFromValues(205,	"中３");
			addRowFromValues(27,	"右３");
			addRowFromValues(206,	"右３");
			addRowFromValues(207,	"右３");
			addRowFromValues(28,	"左本");
			addRowFromValues(208,	"左本");
			addRowFromValues(209,	"左本");
			addRowFromValues(29,	"中本");
			addRowFromValues(210,	"中本");
			addRowFromValues(211,	"中本");
			addRowFromValues(30,	"右本");
			addRowFromValues(212,	"右本");
			addRowFromValues(213,	"右本");
			addRowFromValues(31,	"空三振");
			addRowFromValues(214,	"見三振");
			addRowFromValues(241,	"バ三振");
			addRowFromValues(32,	"暴振逃");
			addRowFromValues(33,	"逸振逃");
			addRowFromValues(34,	"四球");
			addRowFromValues(35,	"敬遠");
			addRowFromValues(36,	"死球");
			addRowFromValues(37,	"打妨");
			addRowFromValues(38,	"守妨");
			addRowFromValues(39,	"投犠野");
			addRowFromValues(215,	"捕犠野");
			addRowFromValues(216,	"一犠野");
			addRowFromValues(217,	"二犠野");
			addRowFromValues(218,	"三犠野");
			addRowFromValues(219,	"遊犠野");
			addRowFromValues(220,	"左犠野");
			addRowFromValues(221,	"中犠野");
			addRowFromValues(222,	"右犠野");
			addRowFromValues(40,	"投ゴロ");
			addRowFromValues(41,	"捕ゴロ");
			addRowFromValues(42,	"一ゴロ");
			addRowFromValues(43,	"二ゴロ");
			addRowFromValues(44,	"三ゴロ");
			addRowFromValues(45,	"遊ゴロ");
			addRowFromValues(46,	"左ゴロ");
			addRowFromValues(47,	"中ゴロ");
			addRowFromValues(48,	"右ゴロ");
			addRowFromValues(49,	"投飛");
			addRowFromValues(50,	"捕飛");
			addRowFromValues(51,	"一飛");
			addRowFromValues(52,	"二飛");
			addRowFromValues(53,	"三飛");
			addRowFromValues(54,	"遊飛");
			addRowFromValues(55,	"左飛");
			addRowFromValues(56,	"中飛");
			addRowFromValues(57,	"右飛");
			addRowFromValues(58,	"投直");
			addRowFromValues(59,	"捕直");
			addRowFromValues(60,	"一直");
			addRowFromValues(61,	"二直");
			addRowFromValues(62,	"三直");
			addRowFromValues(63,	"遊直");
			addRowFromValues(64,	"左直");
			addRowFromValues(65,	"中直");
			addRowFromValues(66,	"右直");
			addRowFromValues(67,	"投犠打");
			addRowFromValues(68,	"捕犠打");
			addRowFromValues(69,	"一犠打");
			addRowFromValues(70,	"二犠打");
			addRowFromValues(71,	"三犠打");
			addRowFromValues(72,	"遊犠打");
			addRowFromValues(223,	"左犠打");
			addRowFromValues(224,	"中犠打");
			addRowFromValues(225,	"右犠打");
			addRowFromValues(73,	"投犠飛");
			addRowFromValues(74,	"捕犠飛");
			addRowFromValues(75,	"一犠飛");
			addRowFromValues(76,	"二犠飛");
			addRowFromValues(77,	"三犠飛");
			addRowFromValues(78,	"遊犠飛");
			addRowFromValues(79,	"左犠飛");
			addRowFromValues(80,	"中犠飛");
			addRowFromValues(81,	"右犠飛");
			addRowFromValues(82,	"投邪飛");
			addRowFromValues(83,	"捕邪飛");
			addRowFromValues(84,	"一邪飛");
			addRowFromValues(85,	"二邪飛");
			addRowFromValues(86,	"三邪飛");
			addRowFromValues(87,	"遊邪飛");
			addRowFromValues(88,	"左邪飛");
			addRowFromValues(89,	"中邪飛");
			addRowFromValues(90,	"右邪飛");
			addRowFromValues(232,	"投邪直");
			addRowFromValues(233,	"捕邪直");
			addRowFromValues(234,	"一邪直");
			addRowFromValues(235,	"二邪直");
			addRowFromValues(236,	"三邪直");
			addRowFromValues(237,	"遊邪直");
			addRowFromValues(238,	"左邪直");
			addRowFromValues(239,	"中邪直");
			addRowFromValues(240,	"右邪直");
			addRowFromValues(91,	"投併打");
			addRowFromValues(92,	"捕併打");
			addRowFromValues(93,	"一併打");
			addRowFromValues(94,	"二併打");
			addRowFromValues(95,	"三併打");
			addRowFromValues(96,	"遊併打");
			addRowFromValues(97,	"左併打");
			addRowFromValues(98,	"中併打");
			addRowFromValues(99,	"右併打");
			addRowFromValues(100,	"投失");
			addRowFromValues(101,	"捕失");
			addRowFromValues(102,	"一失");
			addRowFromValues(103,	"二失");
			addRowFromValues(104,	"三失");
			addRowFromValues(105,	"遊失");
			addRowFromValues(106,	"左失");
			addRowFromValues(107,	"中失");
			addRowFromValues(108,	"右失");
			addRowFromValues(109,	"投野選");
			addRowFromValues(110,	"捕野選");
			addRowFromValues(111,	"一野選");
			addRowFromValues(112,	"二野選");
			addRowFromValues(113,	"三野選");
			addRowFromValues(114,	"遊野選");
			addRowFromValues(226,	"左野選");
			addRowFromValues(227,	"中野選");
			addRowFromValues(228,	"右野選");
			addRowFromValues(115,	"犠打失");
			addRowFromValues(116,	"犠飛失");
			addRowFromValues(117,	"野選失");
			addRowFromValues(229,	"振逃");
		} catch (TypeMismatchException e) {
			e.printStackTrace();
		}
	}

	public static BattingResultDataTable getInstance() {
		return instance;
  }

}
